"""Markdown reporting, for a pull-request comment (task 7.2).

A PR comment is read by someone who did not run the evals and cannot see the
terminal. That makes the honesty rules matter *more* here than in the console,
not less: a reviewer who reads "cost $0.0000" in a comment has no way to check
whether that means free or unpriced, and will act on the number as written.

So the rules come from `reporting.console` — `UNKNOWN`, `pass_counts`,
`format_cost` — rather than being restated. A second set would drift, and the
first time it did, the comment and the terminal would disagree about whether a
build passed with nothing to say which was right.

Markdown is generated by hand rather than through a library. The output is a
handful of tables, the escaping rules are three characters wide, and a
dependency whose renderer changed would silently reshape every comment.
"""

from __future__ import annotations

from evalstand.models import Run
from evalstand.reporting.console import UNKNOWN, format_cost, format_score, pass_counts

__all__ = ["render_markdown"]

_MAX_CELL = 60
"""Long outputs are truncated. A PR comment that pastes a 4000-token completion
buries the summary it exists to deliver, and GitHub silently hides comments past
65 536 characters — a report nobody can see is worse than a short one."""


def _escape(value: object) -> str:
    """Make a value safe inside a table cell.

    Only three characters can break a markdown table: a pipe ends the cell, and
    a newline ends the row. Backticks are left alone — model output often
    contains code, and mangling it would make the comment harder to read for a
    problem that does not exist.
    """
    text = str(value).replace("|", "\\|").replace("\n", " ").replace("\r", " ")
    return text if len(text) <= _MAX_CELL else text[: _MAX_CELL - 3] + "..."


def _cases(run: Run) -> str:
    passed, judged = pass_counts(run)
    return UNKNOWN if not judged else f"{passed}/{judged}"


def _summary_table(runs: list[Run]) -> list[str]:
    """One row per eval, per scorer.

    Per scorer rather than one figure per eval, for the reason
    `Run.mean_scores_by_scorer` gives: averaging across scorers that measure
    different things produces a number that means nothing.
    """
    lines = [
        "| eval | scorer | mean | passed | cost |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for run in runs:
        means = run.mean_scores_by_scorer()
        cost = format_cost([run])
        if not means:
            # An eval whose every scorer errored still gets a row. Omitting it
            # would leave a reviewer believing it was never part of the run.
            lines.append(
                f"| {_escape(run.name)} | {UNKNOWN} | {UNKNOWN} | {_cases(run)} | {cost} |"
            )
            continue
        for scorer_name, mean in sorted(means.items()):
            lines.append(
                f"| {_escape(run.name)} | {_escape(scorer_name)} | "
                f"{format_score(mean)} | {_cases(run)} | {cost} |"
            )
    return lines


def _attention(runs: list[Run]) -> list[str]:
    """Cases a reviewer should look at: wrong answers, crashes, and the
    unmeasured.

    `unmeasured` is listed beside failures deliberately. A scorer that broke
    leaves the task's performance unknown, and a reviewer who sees only the mean
    would read that silence as success.
    """
    rows: list[str] = []
    for run in runs:
        for result in run.results:
            if result.error:
                rows.append(
                    f"| {_escape(run.name)} | {_escape(result.case_id)} | "
                    f"task error | {_escape(result.error)} |"
                )
                continue

            errored = [s for s in result.scores if s.error]
            if errored and len(errored) == len(result.scores):
                rows.append(
                    f"| {_escape(run.name)} | {_escape(result.case_id)} | "
                    f"unmeasured | {_escape(errored[0].error)} |"
                )
                continue

            failed = [s for s in result.scores if s.passed is False]
            if failed:
                names = ", ".join(s.scorer_name for s in failed)
                rows.append(
                    f"| {_escape(run.name)} | {_escape(result.case_id)} | "
                    f"failed {_escape(names)} | {_escape(result.output)} |"
                )

    if not rows:
        return []
    return [
        "",
        "### Needs attention",
        "",
        "| eval | case | reason | detail |",
        "| --- | --- | --- | --- |",
        *rows,
    ]


def _cost_note(runs: list[Run]) -> list[str]:
    """State plainly when the total is a lower bound.

    `total_cost_usd` sums what is known, so a run with unpriced calls cost *at
    least* that much. A reviewer shown the bare figure would understate the
    bill, which is the same class of error as a false pass: quietly wrong in the
    direction that costs money.
    """
    unpriced = sum(run.unpriced_call_count for run in runs)
    if not unpriced:
        return []
    return [
        "",
        f"> {unpriced} model call{'' if unpriced == 1 else 's'} could not be priced, "
        f"so the cost above is a lower bound.",
    ]


def render_markdown(
    runs: list[Run],
    *,
    threshold: float | None = None,
    wall_seconds: float | None = None,
) -> str:
    """A PR-comment body for one batch of runs.

    `threshold` is stated when given, because a reviewer needs to know which bar
    the numbers were judged against — a mean of 0.82 is a pass or a failure
    depending on a number that lives in a CI config they cannot see.
    """
    if not runs:
        # Distinct from a passing run. "No evals ran" and "every eval passed"
        # are opposite findings, and a comment that showed an empty table for
        # both would let a broken collection read as success.
        return "## evalstand\n\nNo evals ran."

    lines = ["## evalstand", "", *_summary_table(runs)]
    lines += _cost_note(runs)
    lines += _attention(runs)

    breaches = [
        (run.name, run.mean_score)
        for run in runs
        if threshold is not None and run.mean_score is not None and run.mean_score < threshold
    ]
    if breaches:
        lines += ["", f"**Below the threshold of {threshold:.2f}:**", ""]
        lines += [f"- `{name}` scored {format_score(mean)}" for name, mean in breaches]

    errored_scores = sum(run.errored_score_count for run in runs)
    if errored_scores:
        lines += [
            "",
            f"> {errored_scores} score{'' if errored_scores == 1 else 's'} errored and "
            f"{'is' if errored_scores == 1 else 'are'} excluded from the means above, "
            f"so those means cover fewer cases than the run contains.",
        ]

    if wall_seconds is not None:
        lines += [
            "",
            f"<sub>{len(runs)} eval{'' if len(runs) == 1 else 's'} in {wall_seconds:.1f}s</sub>",
        ]

    return "\n".join(lines) + "\n"
