"""The single page the browser loads (task 8.2).

HTMX is vendored as a `<script>` tag rather than fetched from a CDN. `serve` is
a local-first command — a user runs it on a laptop, sometimes offline, often on
a network that cannot reach a CDN — and a page whose interactivity depends on
an outbound request is a page that silently becomes a static table.

The stylesheet is the artifact renderer's, imported rather than copied. Two
copies of a colour scheme drift, and the whole point of the five status names
is that `fail` and `unmeasured` never look alike.
"""

from __future__ import annotations

from pathlib import Path

from evalstand.reporting.html import STYLE

HTMX_VERSION = "2.0.4"
HTMX_URL = f"https://unpkg.com/htmx.org@{HTMX_VERSION}/dist/htmx.min.js"
"""Where the vendored copy came from, for anyone updating it.

Recorded as a constant rather than a comment so a test can assert the page
embeds the file and does not *fetch* this.
"""

HTMX_SHA256 = "e209dda5c8235479f3166defc7750e1dbcd5a5c1808b7792fc2e6733768fb447"
"""The digest of the vendored file, asserted by the suite.

A vendored dependency nobody checks is a file anyone can replace. Pinning the
digest makes a substitution fail a test rather than ship.
"""

STATIC = Path(__file__).parent / "static"


def htmx_source() -> str:
    """The vendored htmx, read from the package.

    Read at call time rather than at import: the page is rendered once per
    request and holding 50KB of JavaScript in module state for the lifetime of
    a process that may never serve a page is not worth the microsecond.
    """
    return (STATIC / "htmx.min.js").read_text(encoding="utf-8")


_EXTRA_STYLE = """
.layout { display: grid; grid-template-columns: minmax(0, 1fr); gap: 1.5rem; }
@media (min-width: 60rem) { .layout { grid-template-columns: 22rem minmax(0, 1fr); } }
.row { cursor: pointer; }
.row:hover { background: var(--panel); }
.totals { display: grid; grid-template-columns: auto 1fr; gap: 0.35rem 1rem; margin: 1rem 0; }
.totals dt { color: var(--muted); }
.totals dd { margin: 0; }
.empty { color: var(--muted); padding: 2rem 0; }
.live { display: inline-block; padding: 0.1rem 0.5rem; border-radius: 0.25rem;
        background: var(--panel); color: var(--muted); font-size: 0.85em; }
.live.on { color: var(--pass); }
"""


def index(*, htmx: str) -> str:
    """The whole application: a run list, a detail pane, and a live table.

    `htmx` is the library source, injected so the caller decides where it comes
    from — a vendored file in production, a stub in a test that only checks the
    markup.
    """
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>evalstand</title>
<style>{STYLE}{_EXTRA_STYLE}</style>
<script>{htmx}</script>
</head>
<body>
<main>
<h1>evalstand</h1>
<p class="sub">Local run history. <span id="live" class="live">not live</span></p>

<div class="layout">
  <section>
    <h2>Runs</h2>
    <div id="runs" hx-get="/ui/runs" hx-trigger="load" hx-swap="innerHTML">
      <p class="empty">Loading&hellip;</p>
    </div>
  </section>

  <section>
    <div id="detail">
      <p class="empty">Select a run to see its cases.</p>
    </div>
  </section>
</div>

<footer>
Generated by evalstand. A dash means a value could not be determined &mdash;
never that it is zero. Score differences carry no significance testing.
</footer>
</main>

<script>
// The live table, when a run is streaming. Kept to a few lines on purpose:
// every number on this page is rendered by the server, so there is no
// client-side model here to disagree with it — only row insertion.
(function () {{
  var badge = document.getElementById("live");
  var source = new EventSource("/ui/live");

  source.addEventListener("result", function (event) {{
    var html = JSON.parse(event.data);
    var detail = document.getElementById("detail");
    var body = detail.querySelector("tbody");
    if (!body) {{ return; }}

    var row = document.createElement("tbody");
    row.innerHTML = html;
    var incoming = row.firstElementChild;
    if (!incoming) {{ return; }}

    // Replace by id rather than append: a repeat of a case already on screen
    // is the same row updated, and appending would show one case twice with
    // two different scores.
    var existing = document.getElementById(incoming.id);
    if (existing) {{ existing.replaceWith(incoming); }} else {{ body.appendChild(incoming); }}

    badge.textContent = "live";
    badge.classList.add("on");
  }});

  source.addEventListener("done", function () {{
    badge.textContent = "finished";
    badge.classList.remove("on");
  }});

  // A failed connection is not an error worth shouting about: `serve` is
  // usually browsing history with nothing running, and EventSource retries on
  // its own.
  source.onerror = function () {{
    badge.textContent = "not live";
    badge.classList.remove("on");
  }};
}})();
</script>
</body>
</html>
"""
